# Generated by Django 5.2.7 on 2025-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cleared_at_for_participant_1',
            field=models.DateTimeField(blank=True, help_text='Messages before this timestamp are hidden for participant 1', null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='cleared_at_for_participant_2',
            field=models.DateTimeField(blank=True, help_text='Messages before this timestamp are hidden for participant 2', null=True),
        ),
    ]
